baseurl = "https://gfmedstudent.netlify.app"
languageCode = "pl"
paginate = 6
summaryLength = "10"
theme = "parsa-hugo"
title = "@gfmedstudent Blog"
[[menu.main]]
hasChildren = true
name = "Homepage"
url = ""
weight = 1
[[menu.main]]
name = "About"
url = "about"
weight = 2
[[menu.main]]
name = "Contact"
url = "contact"
weight = 3
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
address = ""
author = "Magdalena"
author_image = "images/banner-img.png"
bio = "Lekarka, doktorantka, "
contact_form_action = "#"
copyright = "Copyright &copy; 2020 a theme by [themefisher.com](themefisher.com)"
description = "This is meta description"
email = "theglutenfreestory@gmail.com"
google_analitycs_id = "Your ID"
home = "Home"
layout = "1"
logo = "images/logo.png"
mobile = ""
preloader = true
search = true
[params.cookies]
enable = true
expire_days = 2
[params.instafeed]
access_token = "IGQVJYQU1YY0lHZADFraWJ1dFdxb05BMWdXcFRvNDhfcnFOQ0U1ZAnhDaVlZAX2JMN1l5bkdhSlk4dGVxOHkzck1WTlNlSEYwd3NYbm9iTWQtbDlqVWpxWHAwMVV4TWQ3bzJsTzJLYnFmd1ZA5WjdWb09VTAZDZD"
enable = true
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/headroom/headroom.js"
[[params.plugins.js]]
link = "plugins/instafeed/instafeed.min.js"
[[params.plugins.js]]
link = "plugins/masonry/masonry.js"
[[params.plugins.js]]
link = "plugins/reading-time/readingTime.min.js"
[[params.plugins.js]]
link = "plugins/smooth-scroll/smooth-scroll.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[[params.social]]
icon = "ti-facebook"
url = "#"
[[params.social]]
icon = "ti-twitter-alt"
url = "#"
[[params.social]]
icon = "ti-linkedin"
url = "#"
[[params.social]]
icon = "ti-github"
url = "#"
